/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ipf.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions)
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Empty003" position={[-6.15, 0, -2.55]} rotation={[0, 0.09, 0]} />
      <mesh
        name="Cone"
        geometry={nodes.Cone.geometry}
        material={nodes.Cone.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone002"
        geometry={nodes.Cone002.geometry}
        material={nodes.Cone002.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone004"
        geometry={nodes.Cone004.geometry}
        material={nodes.Cone004.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone025"
        geometry={nodes.Cone025.geometry}
        material={nodes.Cone025.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone027"
        geometry={nodes.Cone027.geometry}
        material={nodes.Cone027.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone032"
        geometry={nodes.Cone032.geometry}
        material={nodes.Cone032.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone033"
        geometry={nodes.Cone033.geometry}
        material={nodes.Cone033.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone034"
        geometry={nodes.Cone034.geometry}
        material={nodes.Cone034.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone035"
        geometry={nodes.Cone035.geometry}
        material={nodes.Cone035.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone061"
        geometry={nodes.Cone061.geometry}
        material={nodes.Cone061.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone062"
        geometry={nodes.Cone062.geometry}
        material={nodes.Cone062.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone063"
        geometry={nodes.Cone063.geometry}
        material={nodes.Cone063.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone064"
        geometry={nodes.Cone064.geometry}
        material={nodes.Cone064.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone065"
        geometry={nodes.Cone065.geometry}
        material={nodes.Cone065.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone066"
        geometry={nodes.Cone066.geometry}
        material={nodes.Cone066.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone067"
        geometry={nodes.Cone067.geometry}
        material={nodes.Cone067.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone068"
        geometry={nodes.Cone068.geometry}
        material={nodes.Cone068.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone069"
        geometry={nodes.Cone069.geometry}
        material={nodes.Cone069.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone070"
        geometry={nodes.Cone070.geometry}
        material={nodes.Cone070.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone071"
        geometry={nodes.Cone071.geometry}
        material={nodes.Cone071.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone096"
        geometry={nodes.Cone096.geometry}
        material={nodes.Cone096.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone097"
        geometry={nodes.Cone097.geometry}
        material={nodes.Cone097.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone098"
        geometry={nodes.Cone098.geometry}
        material={nodes.Cone098.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone099"
        geometry={nodes.Cone099.geometry}
        material={nodes.Cone099.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone106"
        geometry={nodes.Cone106.geometry}
        material={nodes.Cone106.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone107"
        geometry={nodes.Cone107.geometry}
        material={nodes.Cone107.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone133"
        geometry={nodes.Cone133.geometry}
        material={nodes.Cone133.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone134"
        geometry={nodes.Cone134.geometry}
        material={nodes.Cone134.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone135"
        geometry={nodes.Cone135.geometry}
        material={nodes.Cone135.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone136"
        geometry={nodes.Cone136.geometry}
        material={nodes.Cone136.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone137"
        geometry={nodes.Cone137.geometry}
        material={nodes.Cone137.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone138"
        geometry={nodes.Cone138.geometry}
        material={nodes.Cone138.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone140"
        geometry={nodes.Cone140.geometry}
        material={nodes.Cone140.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone141"
        geometry={nodes.Cone141.geometry}
        material={nodes.Cone141.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone142"
        geometry={nodes.Cone142.geometry}
        material={nodes.Cone142.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cone143"
        geometry={nodes.Cone143.geometry}
        material={nodes.Cone143.material}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-2, -1.25, 0]} scale={10.83} />
    </group>
  )
}

useGLTF.preload('/ipf.glb')
