/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/logo5.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions.action1);
  useEffect(() => {
    Object.entries(actions).forEach(([key, value]) => {
      value.play().setEffectiveTimeScale(0.5)
    });
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[7.91, 11.43, 6.52]}>
        {/* <pointLight intensity={2000} decay={2} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <group position={[7.91, 0.85, 6.52]}>
        {/* <pointLight intensity={2000} decay={2} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <group position={[7.91, 11.43, -6.86]}>
        {/* <pointLight intensity={2000} decay={2} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <group position={[7.91, 0.85, -6.86]}>
        {/* <pointLight intensity={2000} decay={2} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <group name="P001" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone037.geometry} material={nodes.Cone037.material} />
        <mesh geometry={nodes.Cone037_1.geometry} material={nodes.Cone037_1.material} />
      </group>
      <group name="P002" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone047.geometry} material={nodes.Cone047.material} />
        <mesh geometry={nodes.Cone047_1.geometry} material={nodes.Cone047_1.material} />
      </group>
      <group name="P003" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone048.geometry} material={nodes.Cone048.material} />
        <mesh geometry={nodes.Cone048_1.geometry} material={nodes.Cone048_1.material} />
      </group>
      <group name="P004" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone049.geometry} material={nodes.Cone049.material} />
        <mesh geometry={nodes.Cone049_1.geometry} material={nodes.Cone049_1.material} />
      </group>
      <group name="P005" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone050.geometry} material={nodes.Cone050.material} />
        <mesh geometry={nodes.Cone050_1.geometry} material={nodes.Cone050_1.material} />
      </group>
      <group name="P006" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone051.geometry} material={nodes.Cone051.material} />
        <mesh geometry={nodes.Cone051_1.geometry} material={nodes.Cone051_1.material} />
      </group>
      <group name="P007" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone052.geometry} material={nodes.Cone052.material} />
        <mesh geometry={nodes.Cone052_1.geometry} material={nodes.Cone052_1.material} />
      </group>
      <group name="P008" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone053.geometry} material={nodes.Cone053.material} />
        <mesh geometry={nodes.Cone053_1.geometry} material={nodes.Cone053_1.material} />
      </group>
      <group name="P010" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone054.geometry} material={nodes.Cone054.material} />
        <mesh geometry={nodes.Cone054_1.geometry} material={nodes.Cone054_1.material} />
      </group>
      <group name="P012" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone055.geometry} material={nodes.Cone055.material} />
        <mesh geometry={nodes.Cone055_1.geometry} material={nodes.Cone055_1.material} />
      </group>
      <group name="P014" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone056.geometry} material={nodes.Cone056.material} />
        <mesh geometry={nodes.Cone056_1.geometry} material={nodes.Cone056_1.material} />
      </group>
      <group name="P018" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone057.geometry} material={nodes.Cone057.material} />
        <mesh geometry={nodes.Cone057_1.geometry} material={nodes.Cone057_1.material} />
      </group>
      <group name="P009" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone058.geometry} material={nodes.Cone058.material} />
        <mesh geometry={nodes.Cone058_1.geometry} material={nodes.Cone058_1.material} />
      </group>
      <group name="P011" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone059.geometry} material={nodes.Cone059.material} />
        <mesh geometry={nodes.Cone059_1.geometry} material={nodes.Cone059_1.material} />
      </group>
      <group name="P015" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone061.geometry} material={nodes.Cone061.material} />
        <mesh geometry={nodes.Cone061_1.geometry} material={nodes.Cone061_1.material} />
      </group>
      <group name="P016" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone062.geometry} material={nodes.Cone062.material} />
        <mesh geometry={nodes.Cone062_1.geometry} material={nodes.Cone062_1.material} />
      </group>
      <group name="F001" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone065.geometry} material={nodes.Cone065.material} />
        <mesh geometry={nodes.Cone065_1.geometry} material={nodes.Cone065_1.material} />
      </group>
      <group name="F002" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone066.geometry} material={nodes.Cone066.material} />
        <mesh geometry={nodes.Cone066_1.geometry} material={nodes.Cone066_1.material} />
      </group>
      <group name="F003" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone067.geometry} material={nodes.Cone067.material} />
        <mesh geometry={nodes.Cone067_1.geometry} material={nodes.Cone067_1.material} />
      </group>
      <group name="F005" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone068.geometry} material={nodes.Cone068.material} />
        <mesh geometry={nodes.Cone068_1.geometry} material={nodes.Cone068_1.material} />
      </group>
      <group name="F004" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone069.geometry} material={nodes.Cone069.material} />
        <mesh geometry={nodes.Cone069_1.geometry} material={nodes.Cone069_1.material} />
      </group>
      <group name="F006" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone071.geometry} material={nodes.Cone071.material} />
        <mesh geometry={nodes.Cone071_1.geometry} material={nodes.Cone071_1.material} />
      </group>
      <group name="F007" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone072.geometry} material={nodes.Cone072.material} />
        <mesh geometry={nodes.Cone072_1.geometry} material={nodes.Cone072_1.material} />
      </group>
      <group name="F008" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone073.geometry} material={nodes.Cone073.material} />
        <mesh geometry={nodes.Cone073_1.geometry} material={nodes.Cone073_1.material} />
      </group>
      <group name="F009" position={[0.45, 1.31, -0.67]} rotation={[2.09, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone075.geometry} material={nodes.Cone075.material} />
        <mesh geometry={nodes.Cone075_1.geometry} material={nodes.Cone075_1.material} />
      </group>
      <group name="I001" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone076.geometry} material={nodes.Cone076.material} />
        <mesh geometry={nodes.Cone076_1.geometry} material={nodes.Cone076_1.material} />
      </group>
      <group name="I002" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone077.geometry} material={nodes.Cone077.material} />
        <mesh geometry={nodes.Cone077_1.geometry} material={nodes.Cone077_1.material} />
      </group>
      <group name="I003" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone078.geometry} material={nodes.Cone078.material} />
        <mesh geometry={nodes.Cone078_1.geometry} material={nodes.Cone078_1.material} />
      </group>
      <group name="I004" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone079.geometry} material={nodes.Cone079.material} />
        <mesh geometry={nodes.Cone079_1.geometry} material={nodes.Cone079_1.material} />
      </group>
      <group name="I005" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone080.geometry} material={nodes.Cone080.material} />
        <mesh geometry={nodes.Cone080_1.geometry} material={nodes.Cone080_1.material} />
      </group>
      <group name="I006" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone081.geometry} material={nodes.Cone081.material} />
        <mesh geometry={nodes.Cone081_1.geometry} material={nodes.Cone081_1.material} />
      </group>
      <group name="I007" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone082.geometry} material={nodes.Cone082.material} />
        <mesh geometry={nodes.Cone082_1.geometry} material={nodes.Cone082_1.material} />
      </group>
      <group name="I008" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone083.geometry} material={nodes.Cone083.material} />
        <mesh geometry={nodes.Cone083_1.geometry} material={nodes.Cone083_1.material} />
      </group>
      <group name="I009" position={[0.45, 2.13, 2.08]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone084.geometry} material={nodes.Cone084.material} />
        <mesh geometry={nodes.Cone084_1.geometry} material={nodes.Cone084_1.material} />
      </group>
      <group name="P013" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone085.geometry} material={nodes.Cone085.material} />
        <mesh geometry={nodes.Cone085_1.geometry} material={nodes.Cone085_1.material} />
      </group>
      <group name="P017" position={[0.45, 1.33, 0.64]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.78}>
        <mesh geometry={nodes.Cone086.geometry} material={nodes.Cone086.material} />
        <mesh geometry={nodes.Cone086_1.geometry} material={nodes.Cone086_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/logo5.gltf')
