/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/new.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    Object.entries(actions).forEach(([key, value]) => {
      value.play().setEffectiveTimeScale(0.5)
    });
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[15.07, 3.91, -0.14]} rotation={[1.57, -0.07, -1.59]}>
        {/* <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={39.6} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <mesh
        name="Red3"
        geometry={nodes.Red3.geometry}
        material={nodes.Red3.material}
        position={[0.83, 6.58, 1.95]}
        rotation={[-Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black008.geometry}
          material={nodes.Black008.material}
          position={[-0.05, 0, 0.97]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh geometry={nodes.Black013.geometry} material={nodes.Black013.material} position={[-0.04, 0, 3]} />
        <mesh
          geometry={nodes.Black017.geometry}
          material={nodes.Black017.material}
          position={[-0.05, 0, 3.96]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </mesh>
      <mesh
        name="Red2"
        geometry={nodes.Red2.geometry}
        material={nodes.Red2.material}
        position={[0.83, 8.23, 1.95]}
        rotation={[-Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black007.geometry}
          material={nodes.Black007.material}
          position={[0, 0, 0.97]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh geometry={nodes.Black014.geometry} material={nodes.Black014.material} position={[0.01, 0, 3]} />
        <mesh
          geometry={nodes.Black016.geometry}
          material={nodes.Black016.material}
          position={[0, 0, 3.96]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </mesh>
      <mesh
        name="Red8"
        geometry={nodes.Red8.geometry}
        material={nodes.Red8.material}
        position={[0.83, 4.19, 2.47]}
        rotation={[0, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black003.geometry}
          material={nodes.Black003.material}
          position={[-0.01, 0, -2.02]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh geometry={nodes.Green009.geometry} material={nodes.Green009.material} position={[0.01, 0, -3]} />
      </mesh>
      <mesh
        name="Red7"
        geometry={nodes.Red7.geometry}
        material={nodes.Red7.material}
        position={[0.83, 2.59, 2.47]}
        rotation={[0, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black002.geometry}
          material={nodes.Black002.material}
          position={[-0.02, 0, -2.02]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh geometry={nodes.Green008.geometry} material={nodes.Green008.material} position={[-0.01, 0, -3]} />
      </mesh>
      <mesh
        name="Red6"
        geometry={nodes.Red6.geometry}
        material={nodes.Red6.material}
        position={[0.83, 1.77, 1.95]}
        rotation={[-Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black011.geometry}
          material={nodes.Black011.material}
          position={[0, 0, 0.97]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh geometry={nodes.Green003.geometry} material={nodes.Green003.material} position={[0.02, 0, 3]} />
      </mesh>
      <mesh
        name="Red5"
        geometry={nodes.Red5.geometry}
        material={nodes.Red5.material}
        position={[0.83, 3.38, 1.95]}
        rotation={[Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black010.geometry}
          material={nodes.Black010.material}
          position={[-0.05, 0, 0.97]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh geometry={nodes.Green002.geometry} material={nodes.Green002.material} position={[-0.01, 0, 3]} />
        <mesh
          geometry={nodes.Green005.geometry}
          material={nodes.Green005.material}
          position={[-0.04, 0, 3.95]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </mesh>
      <mesh
        name="Red4"
        geometry={nodes.Red4.geometry}
        material={nodes.Red4.material}
        position={[0.83, 5.02, 1.95]}
        rotation={[-Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black009.geometry}
          material={nodes.Black009.material}
          position={[0.03, 0, 0.97]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh geometry={nodes.Green001.geometry} material={nodes.Green001.material} position={[0.02, 0, 3]} />
        <mesh
          geometry={nodes.Green006.geometry}
          material={nodes.Green006.material}
          position={[-0.02, 0, 3.95]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </mesh>
      <mesh
        name="Red1"
        geometry={nodes.Red1.geometry}
        material={nodes.Red1.material}
        position={[0.83, 7.43, 2.47]}
        rotation={[0, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black005.geometry}
          material={nodes.Black005.material}
          position={[-0.02, 0, -2.02]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.Black015.geometry}
          material={nodes.Black015.material}
          position={[-0.02, 0, -5.01]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </mesh>
      <mesh
        name="Red9"
        geometry={nodes.Red9.geometry}
        material={nodes.Red9.material}
        position={[0.83, 5.82, 2.47]}
        rotation={[0, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Black004.geometry}
          material={nodes.Black004.material}
          position={[-0.01, 0, -2.02]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh geometry={nodes.Black012.geometry} material={nodes.Black012.material} position={[-0.01, 0, -3]} />
        <mesh
          geometry={nodes.Green004.geometry}
          material={nodes.Green004.material}
          position={[0.01, 0, -5]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </mesh>
      <mesh
        name="Black001"
        geometry={nodes.Black001.geometry}
        material={nodes.Black001.material}
        position={[0.83, 0.94, 0.45]}
        rotation={[-Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Green007.geometry}
          material={nodes.Green007.material}
          position={[-0.02, 0, 0.98]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </mesh>
      <mesh
        name="Black006"
        geometry={nodes.Black006.geometry}
        material={nodes.Black006.material}
        position={[0.83, 9.03, 0.45]}
        rotation={[-Math.PI, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Cone046.geometry}
          material={nodes.Cone046.material}
          position={[0, 0, 0.98]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/new.gltf')
